### ISSUE TITLE
How do you cancel a scan?

### ISSUE THREAD

**Issue by garr741** [square/whorlwind#11]
In my app, I initiate a scan with `whorlwind.read()`, and I pop a dialog. The dialog has a cancel option, so if that is clicked, how do I cancel the scan?

**Comment by Mauin** [comment]
Unsubscribing the Subscription will also cancel the fingerprint operation and disable the fingerprint reader for this operation.

**Comment by mattprecious** [comment]
Yep. Unsubscribe from the returned subscription to cancel.
