### ISSUE TITLE
The write method should throw when writing fails

### ISSUE THREAD

**Issue by grandstaish** [square/whorlwind#16]
RSA encryption only allows 256 bytes to be encrypted, so if you try to write a large value then Whorlwind will silently fail with a log in the following format:

```
Failed to write value for <name>
javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
```

Of course there are other reasons why this might fail too, but this one is probably one that people will run into often. It would be better to be able to handle this as an error. An alternative solution would be to have this method return a boolean that returns true only when the write was successful.

**Comment by mattprecious** [comment]
Oh, fun. Yeah, this should probably be documented and throw!

**Comment by vanniktech** [comment]
I'm also in favor of throwing here.
