### ISSUE TITLE
Update to use AES cipher and generated symmetric key

### ISSUE THREAD

**Issue by rockaport** [square/whorlwind#19]
This is somewhat related to #18 and before I go through submit a PR I'm wondering if it's something that would be accepted.

1. Store a generated AES symmetric key in shared preferences that will be encrypted/decrypted using the generated RSA public/private key.
2. Encrypt/decrypt shared preference content using [Alice](https://github.com/rockaport/alice) and the symmetric key

**Comment by mattprecious** [comment]
These changes sound pretty complicated and out of scope of what this library is meant to do. If you have a proposal for a simple change then I'll consider it but I don't want to make this library any more complicated than it is right now.

**Comment by rockaport** [comment]
Sounds good, the changes are a little complicated. I'll close this issue out.
