### ISSUE TITLE
rx.Schedulers and io.reactivex.schedulers.Schedulers

### ISSUE THREAD

**Issue by narutouzumaki32** [square/whorlwind#25]
In library `Whorlwind.java` used from `rx.Observable` but in your sample project `io.reactivex.Observable` imported and this conflict confused my environment and I get this error:
`error: incompatible types: io.reactivex.Scheduler cannot be converted to rx.Scheduler`

How can I fix it?
Thanks in advance

**Comment by vanniktech** [comment]
Rx2 variant has not been released yet.

**Comment by JakeWharton** [comment]
You can browse the latest tag to see the sample for its release: https://github.com/square/whorlwind/tree/1.0.1
