### ISSUE TITLE
supported version?

### ISSUE THREAD

**Issue by vishalpatelinexture** [square/whorlwind#4]
question
=========
this lib support all version like 
6.0  or <6.0

and is it support like xiami note 3,Samsung alpha devices  ?

because they are using own API i think  0_0

**Comment by Mauin** [comment]
As Whorlwind is based on the Android Fingerprint APIs, which were only introduced with Android 6.0 it will not have any functionality below 6.0.
MinSdkVersion for this library is 15, but below 23 it will not do any fingerprint operations.

Only the Android Fingerprint APIs are supported as far as I can see, so devices using their own implementations will not work.

**Comment by vishalpatelinexture** [comment]
thanks for immediate  Clearance  ;)
