### ISSUE TITLE
AndroidX version

### ISSUE THREAD

**Issue by sivze** [square/whorlwind#57]
When will the androidX release version will be created for this library?

**Comment by vanniktech** [comment]
It's already ported #56 you can use the snapshot for now

**Comment by sivze** [comment]
@vanniktech thank you but I couldn't be able locate the snapshot, do you mind sharing the link?

**Comment by mattprecious** [comment]
This was released as version 2.1.0: https://github.com/square/whorlwind/blob/master/CHANGELOG.md#version-210-2020-11-23
