### ISSUE TITLE
Androidx Biometric Support

### ISSUE THREAD

**Issue by EnricoMazzu** [square/whorlwind#58]
Hello,

I found this library really interesting. My question is: is there a plan to integrate official Google [androidx biometric library](https://developer.android.com/jetpack/androidx/releases/biometric) ?

It could be a good option providing a way (via an interface definition and a factory, a bridge or another pattern) to switch or use different implementations of the "under the hood" crypto operations / authentication.

I know that probably you want to have a faceless SDK, but providing an optional biometricx based implemetation (maybe in an external module that depends from the core) could provide a more ready to use and scalable solution.

If this sound good, i can work to a fork and trying to submit a pull request.

**Comment by mattprecious** [comment]
No, there's no plans to migrate this project over to the biometrics library, as we've moved off of this internally. I've just marked the project as deprecated, but feel free to fork and migrate!
